name: creta03
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  flutter_speed_dial: ^6.1.0+1
  routemaster: ^1.0.1
  hycop: ^0.2.13
  outline_search_bar: ^2.3.0
  custom_radio_grouped_button: ^2.2.0
  # elegant_radio_button_group: ^0.0.1
  # roundcheckbox: ^2.0.5
  # flutter_awesome_select: ^6.5.0
  # radio_grouped_buttons: ^1.0.1
  group_radio_button: ^1.2.0
  another_xlider: ^1.1.2
  dropdown_button2: ^1.8.9
  url_strategy: ^0.2.0
  # flutter_xlider: ^3.4.0
  flutter_vector_icons: ^2.0.0
  url_launcher: ^6.1.7
  cached_network_image: ^3.2.3
  image_network: ^2.4.1   
  http: ^0.13.5
  universal_html: ^2.2.3
  firebase_core_platform_interface: 4.5.2
  adaptive_scrollbar: ^2.1.2
  mutex: ^3.0.1
  loading_animation_widget: ^1.2.0+4
  #sortedmap: ^0.5.2
  deep_collection: ^1.0.2
  get: ^4.6.5
  dotted_border: ^2.0.0+3
  material_tag_editor: ^0.1.2
  quiver: ^3.2.1
  flex_color_picker: ^3.1.0
  flutter_animate: ^4.0.0
  r_dotted_line_border: ^0.1.1
  flutter_inner_shadow: ^0.0.1
  inner_shadow_widget: ^0.0.3
  confetti: ^0.7.0
  snowfall: ^0.0.2
  parallax_rain: ^1.1.0
  floating_bubbles: ^2.3.0
  starsview: ^0.0.2
  flutter_dropzone: ^3.0.5
  blobs: ^2.0.0
  video_player: ^2.6.1
  # youtube_player_iframe: ^3.1.0
  youtube_player_iframe: ^4.0.4
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  scroll_loop_auto_scroll: ^0.0.5
  widget_and_text_animator: ^1.0.9
  text_to_speech: ^0.2.3
  image_picker: ^0.8.7
  intl: ^0.18.0
  flutter_svg: ^2.0.5
  translator: ^0.1.7
  progress_bar_steppers: ^0.0.2+2
  flutter_sequence_animation: ^4.0.0
  cloud_firestore: ^4.3.1
  flutter_keyboard_visibility: ^5.4.1
  webview_flutter: ^4.0.7     # added by Mai 20230619
  adjusted_html_view_web: ^0.0.1
  flutter_rte: ^0.4.13
  syncfusion_flutter_pdfviewer: ^21.2.10
  appflowy_editor: ^1.1.0
  quill_html_editor: ^2.1.9
  shimmer: ^2.0.0
  circular_reveal_animation: ^2.0.1
  neonpen: ^2.0.5
  simple_tooltip: ^1.2.0
  # pdfx: ^2.3.0
  # internet_file: ^1.2.0
  # universal_platform: ^1.0.0+1
  # performance: ^0.1.0+1
  # html_editor_enhanced: ^2.5.1
  numberpicker: ^2.1.2
  file_picker: ^5.3.1
  flutter_weather_bg_null_safety: ^1.0.0
  weather_animation: ^0.0.2
  just_audio_background: ^0.0.1-beta.10
  flutter_excel: ^1.0.1
  collection: ^1.17.1
  just_audio: ^0.9.34
  audio_session: ^0.1.16
  audio_video_progress_bar: ^1.0.1
  # flutter_custom_clippers: ^2.1.0
  rxdart: ^0.27.7
  fwfh_cached_network_image: ^0.7.0+5
  one_clock: ^1.0.1
  mediasoup_client_flutter: ^0.8.5
  protoo_client: ^0.3.3
  flutter_webrtc: ^0.9.35
  random_string: ^2.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/hycop_config.json
    - assets/creta_logo_blue.png
    - assets/creta_default.png
    - assets/logo_en.png
    - assets/grid.png
    - assets/noise.png
    - assets/youtube.png
    - assets/delete.svg
    - assets/delete_content.svg
    - assets/delete_frame.svg
    - assets/no_image.png
    - assets/ai_tip_image.png
    - assets/creta-photo.png
    - assets/creta-illustration.png
    - assets/creta-digital-art.png
    - assets/creta-popart.png
    - assets/creta-watercolor.png
    - assets/creta-oilpainting.png
    - assets/creta-printmaking.png
    - assets/creta-drawing.png
    - assets/creta-orientalpainting.png
    - assets/creta-outlinedrawing.png
    - assets/creta-crayon.png
    - assets/creta-sketch.png
    - assets/tipImage-1-1.png
    - assets/tipImage-1-2.png
    - assets/tipImage-1-3.png
    - assets/tipImage-1-4.png
    - assets/tipImage-2-1.png
    - assets/tipImage-2-2.png
    - assets/tipImage-2-3.png
    - assets/tipImage-2-4.png
    - assets/bgd.png
    - assets/google__g__logo.svg
    - assets/example.json
    - assets/example.html
    - assets/icon.png
    - assets/landing_page_banner.mp4
    - assets/audio/canone.mp3





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: fonts/Pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: fonts/Pretendard/Pretendard-Light.otf
          weight: 300
        - asset: fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: fonts/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: fonts/Pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: fonts/Pretendard/Pretendard-Black.otf
          weight: 900
    - family: NanumMyeongjo
      fonts:
        - asset: fonts/Nanum_Myeongjo/NanumMyeongjo-Regular.ttf
          weight: 400
        - asset: fonts/Nanum_Myeongjo/NanumMyeongjo-Bold.ttf
          weight: 700
        - asset: fonts/Nanum_Myeongjo/NanumMyeongjo-ExtraBold.ttf
          weight: 800
    - family: Jua
      fonts:
        - asset: fonts/Jua/Jua-Regular.ttf
          weight: 400
    - family: NanumGothic
      fonts:
        - asset: fonts/Nanum_Gothic/NanumGothic-Regular.ttf
          weight: 400
        - asset: fonts/Nanum_Gothic/NanumGothic-Bold.ttf
          weight: 700
        - asset: fonts/Nanum_Gothic/NanumGothic-ExtraBold.ttf
          weight: 800
    - family: NanumPenScript
      fonts:
        - asset: fonts/Nanum_Pen_Script/NanumPenScript-Regular.ttf
          weight: 400
    - family: NotoSansKR
      fonts:
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Thin.otf
          weight: 100
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Light.otf
          weight: 300
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Regular.otf
          weight: 400
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Medium.otf
          weight: 500
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Bold.otf
          weight: 700
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Black.otf
          weight: 900
    - family: Macondo
      fonts:
        - asset: fonts/Macondo/Macondo-Regular.ttf
          weight: 400

